### ISSUE TITLE
make public

### ISSUE THREAD

**Issue by jesseholzerpnnl** [GOCompetition/C3DataUtilities#3]
* create dev branch
* make C3DataUtilities a public repository - done
* add to requirements.txt, setup.py, etc. - done
* Rename Bid-DS-data-model as GO-3-data-model - done
* get GO-3-data-model into setup - done
* make GO-3-data-model public - done
* get GO-3-data-model onto PyPI - done
* get C3DataUtilities onto PyPI - maybe
* update readme.md installation instructions - done
* add use/installation notes - need to revise

**Comment by GOCompetition** [comment]
Repo is now public.

**Comment by ccoffrin** [comment]
I think this issue can be closed?

**Comment by jesseholzerpnnl** [comment]
Closing. We may later put C3DataUtilities onto PyPI. Use/installation notes are good enough.
